"""
Django settings for som_cas project.

Generated by 'django-admin startproject' using Django 1.10.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

import environ
import yaml
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = environ.Path(__file__) - 3

env = environ.Env()

CONFIG_FILE = env.path(
	'SOM_CAS_CONFIG', default=os.path.join(str(BASE_DIR), 'config/conf.yaml')
)

try:
    with open(str(CONFIG_FILE), 'r') as f:
        config = yaml.load(f.read(), Loader=yaml.Loader)
except FileNotFoundError:
    msg = 'Configuration file {} is not defined'
    raise ImproperlyConfigured(msg.format(str(CONFIG_FILE)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=&^f4p(*53em6ptyp+19ch(j0g&^ai0lk+c(mk!f95c1&#a!2g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition
DJANGO_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
	'mama_cas',
	'rosetta'
]

LOCAL_APPS = [
	'som_cas'
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'som_cas.middleware.SomAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'som_cas.middleware.CasLanguageMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'som_cas.SomUser'

AUTHENTICATION_BACKENDS = [
	'som_cas.backends.SocisBackend',
	'som_cas.backends.SomETBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-ES'

LANGUAGES = [
	('ca', _('Catalan')),
	('en', _('English')),
	('es', _('Spanish')),
	('eu', _('Basque')),
	('ga', _('Galician')),
]

LOCALE_PATHS = [
	os.path.join(str(BASE_DIR), 'som_cas/locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(str(BASE_DIR), 'som_cas/static')

# Rosetta conf
ROSETTA_ENABLE_REFLANG = True
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_LOGIN_URL = '/admin'

# Mail conf
ANYMAIL = {
    'SENDGRID_API_KEY': config['sendgrid_api_key'],
    'EMAIL_HOST': 'smtp.sendgrid.net',
    'EMAIL_HOST_USER': 'apikey',
    'EMAIL_HOST_PASSWORD': config['sendgrid_api_key'],
    'EMAIL_PORT': 587,
    'EMAIL_USE_TLS': True,
}
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
DEFAULT_FROM_EMAIL = [config['email']['default_from']]
BCC = [config['email']['bcc']]
