# Generated by Django 2.2.12 on 2020-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som_cas', '0005_auto_20200414_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregistration',
            name='registration_email_sent',
            field=models.BooleanField(default=False, help_text='Check if registration email was sent to the member', verbose_name='Sent registration email'),
        ),
    ]
