# Generated by Django 2.2.17 on 2020-12-04 12:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('som_cas', '0006_agregistration_registration_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the local group', max_length=128, verbose_name='Local group name')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Cities, states and provincies related with this local group', verbose_name='Local group data')),
            ],
            managers=[
                ('lgs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='agregistration',
            managers=[
                ('registrations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assembly',
            managers=[
                ('assemblies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='agregistration',
            name='assembly',
            field=models.ForeignKey(help_text='Asamblea para este censo', on_delete=django.db.models.deletion.CASCADE, to='som_cas.Assembly', verbose_name='Asamblea'),
        ),
        migrations.AlterField(
            model_name='agregistration',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Fecha de registro de la persona socia', verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='agregistration',
            name='member',
            field=models.ForeignKey(help_text='Persona socia para este censo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Persona socia'),
        ),
        migrations.AlterField(
            model_name='agregistration',
            name='registration_email_sent',
            field=models.BooleanField(default=False, help_text='Check if registration email was sent to the member', verbose_name='Email de registro enviado?'),
        ),
        migrations.AlterField(
            model_name='agregistration',
            name='registration_type',
            field=models.CharField(choices=[('in_person', 'In person'), ('virtual', 'Virtual')], help_text='Tipo de cens: si virtual o en persona', max_length=15, verbose_name='Tipo de censo'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='name',
            field=models.CharField(help_text='Name of the assembly, eg: Asamblea 2020', max_length=150, verbose_name='Assembly name'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='local_group',
            field=models.ForeignKey(blank=True, help_text='If assembly is for a local group, set blank for general assembly', limit_choices_to=models.Q(name__isnull=False), null=True, on_delete=django.db.models.deletion.SET_NULL, to='som_cas.LocalGroups', verbose_name='Local Group'),
        ),
    ]
