# Generated by Django 2.2.17 on 2021-01-14 08:33

from django.db import migrations, models
import som_cas.models


class Migration(migrations.Migration):

    dependencies = [
        ('som_cas', '0008_auto_20201222_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgroups',
            name='alias',
            field=models.CharField(blank=True, help_text='Alias of the local group, ex: CT Girona', max_length=128, null=True, verbose_name='Local group alias name'),
        ),
        migrations.AddField(
            model_name='localgroups',
            name='email',
            field=models.CharField(blank=True, help_text='Local group email', max_length=128, null=True, verbose_name='Local group email'),
        ),
        migrations.AddField(
            model_name='localgroups',
            name='full_name',
            field=models.CharField(blank=True, help_text='Name of the local group, ex: Grup Local de Girona', max_length=128, null=True, verbose_name='Local group full name'),
        ),
        migrations.AddField(
            model_name='localgroups',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the local group', null=True, upload_to=som_cas.models.LocalGroups.gls_logo_path, verbose_name='Local group logo'),
        ),
    ]
